on:
  workflow_dispatch:
    inputs:
      node-version:
  pull_request:
  schedule:
    - cron: '0 11 * * *' # Run nightly at 11am UTC (3am Pacific, 6am Eastern)

env:
  E5VFCV_NODE_VERSION: ${{ inputs.node-version || '22' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.E5VFCV_NODE_VERSION }}

      - run: npm clean-install

      - run: npm run tsc

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.E5VFCV_NODE_VERSION }}

      - run: npm clean-install

      - run: npm run prettier:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.E5VFCV_NODE_VERSION }}

      - run: npm clean-install

      - run: npm run lint:check

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          sparse-checkout: '.github/'
      - uses: docker://rhysd/actionlint:1.7.7

